# Generated by Django 6.0.3 on 2026-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=100)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.CharField(max_length=15)),
                ('adventure', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('persons', models.IntegerField()),
                ('payment', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
