# Generated by Django 6.0.3 on 2026-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adventure',
            new_name='adventure3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='date3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='email2',
            new_name='email3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='message',
            new_name='message3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name2',
            new_name='name3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='payment',
            new_name='payment3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='persons',
            new_name='persons3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='phone2',
            new_name='phone3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='price3',
        ),
        migrations.AddField(
            model_name='booking',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
