# Generated by Django 6.0.3 on 2026-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_adventure_booking_adventure3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('roll_no', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
