# Generated by Django 6.0.1 on 2026-02-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dept_head', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_budget', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_emp', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
