# Generated by Django 6.0.1 on 2026-02-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dep',
            name='dept_head',
        ),
    ]
