# Generated by Django 6.0.1 on 2026-02-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_dep_dept_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='DOB',
            new_name='dob',
        ),
    ]
