# Generated by Django 6.0.1 on 2026-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dob_emp_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dep',
            name='dept_head',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
