# Generated by Django 6.0.1 on 2026-02-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dep_dept_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Query', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('admin_rep', models.CharField(blank=True)),
            ],
        ),
    ]
