# Generated by Django 6.0.2 on 2026-02-16 11:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=[cloudinary_storage.storage.MediaCloudinaryStorage], upload_to='images/')),
                ('audio', models.FileField(storage=[cloudinary_storage.storage.RawMediaCloudinaryStorage], upload_to='audio/')),
                ('video', models.FileField(storage=[cloudinary_storage.storage.VideoMediaCloudinaryStorage], upload_to='video/')),
            ],
        ),
    ]
