# Generated by Django 6.0.1 on 2026-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Contact_2', models.IntegerField()),
                ('quali', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('document', models.FileField(null=True, upload_to='doc/')),
                ('audio', models.FileField(null=True, upload_to='audio/')),
                ('video', models.FileField(null=True, upload_to='video/')),
            ],
        ),
    ]
