# Generated by Django 6.0.1 on 2026-01-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='vid',
            field=models.FileField(null=True, upload_to='vid'),
        ),
    ]
