# Generated by Django 6.0.1 on 2026-01-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vid',
            field=models.FileField(null=True, upload_to='vid/'),
        ),
    ]
