# Generated by Django 6.0.3 on 2026-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_department', models.CharField()),
                ('emp_role', models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('user', 'user')], max_length=20)),
            ],
        ),
    ]
