from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.urls import reverse
from urllib.parse import urlencode
import json
import csv


# response in http
# Create your views here.
# simple
def landingpage(req):
    return HttpResponse("hello")
# html ,css code
def landingpage2(req):
    return HttpResponse("<h1 style='color : red ;'>hello</h1>")
# text response
def text_response(req):
    return HttpResponse("this is text response",content_type="text/plain")
# html response
def html_response(req):
    HtML="<h1 style='color :red ;'> hello this html content </h1>"
    return HttpResponse(HtML,content_type="text/html")
# json response
def json_response(req):
    jsondat={'name' : 'jatin''age: 5'}
    jso=json.dumps(jsondat)
    return HttpResponse(jso,content_type="application/json")
# csv
def csv_response(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="employees.csv"'
    writer = csv.writer(response)
    writer.writerow(['Name', 'Department', 'Salary'])
    writer.writerow(['Neeraj', 'IT', 50000])
    writer.writerow(['Ravi', 'HR', 40000])
    return response
# pdf 
def pdf_response(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # Example content (real projects use ReportLab or WeasyPrint)
    response.write("This is a dummy PDF content.")
    return response 

# zipfile
import zipfile
import io
def zip_response(request):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w') as zip_file:
        zip_file.writestr('hello.txt', 'This is inside the ZIP file.')
        zip_file.writestr('readme.txt', 'Generated by Django!')
    response = HttpResponse(buffer.getvalue(), content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename="files.zip"'
    return response
# css
def css_response(request):
    css_content = """
    body {
        background-color: #f0f0f0;
        font-family: Arial, sans-serif;
    }
    h1 {
        color: blue;
        text-align: center;
    }
    """
    return HttpResponse(css_content, content_type="text/css") 

# image
def jpeg_image_response(request):
    with open("Users\DELL\OneDrive\Desktop/sample.jpeg", "rb") as img:
        return HttpResponse(img.read(), content_type="image/jpeg")
    
# render response
# simple
# hardcode
def my_render1(req):
    return render(req,'my_render.html')

def my_render2(req):
    data={
        'name':'jatin'
    }
    return render(req,'my_render.html',data)
# dynamic 
# int 
def my_render3(req,x):
    data={
        'x':x
    }
    return render(req,'my_render.html',data)

def my_render3(req,x):
    data={
        'x':x
    }
    return render(req,'my_render.html',data)

def my_render4(req,name):
    data={
        'name':name
    }
    return render(req,'my_render.html',data)

def my_render5(req,argue):
    data={
        'argue':argue
    }
    return render(req,'my_render.html',data)

# mutiple

def my_render6(req,name,age,qual):
    data={
       'name':name,
        'age':age,
        'qual':qual
    }
    return render(req,'my_render.html',data)

# json responsese


def my_Json1(req):
    data={
         'active':False,
         'active2':False,
         'active3':None
    }
    return JsonResponse(data)
# json me mix


def my_Json2(req):
    data= 'python+django'
    
    return JsonResponse(data,safe=False)
# bool and null
# dumps convert py dta into string

def my_Json3(req):
  data= ['python+django']
  return JsonResponse(data,safe=False)

def my_Json4(req):
  data= 6
  return JsonResponse(data,safe=False)



def my_Json5(req):
  data= (5,8,3,5)
  return JsonResponse(data,safe=False)

# set aur frozen set nhi

# ridirect response

# external
def my_redirect1(req):
     return redirect("https://www.youtube.com/")


# internal
def my_redirect2(req):
     return redirect("landingpage")

# data transfer in response in redirect


def my_redirect3(req):
    url = reverse('my_redirect4')
    data = urlencode({'name': 'sumit', 'age': 19})
    return redirect(f'{url}?{data}')    


def my_redirect4(req):
    print("hello")
    print(req.GET)

# with return in reponse
# get small dict      

def my_redirect5(req):
    url = reverse('my_redirect6')
    data = urlencode({'name': 'sumit', 'age': 15})
    return redirect(f'{url}?{data}')    

def my_redirect6(req):
    data = req.GET.dict()      # dict ban gaya
    return HttpResponse(str(data))   # string me convert kar diya


# def my_redirect6(req):
#     name = req.GET.get("name")
#     age = req.GET.get("age")
#     return HttpResponse(f"Name = {name}, Age = {age}")



