# Generated by Django 6.0.2 on 2026-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
