# Generated by Django 6.0.1 on 2026-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='adhaar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='emp',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
