# Generated by Django 6.0.1 on 2026-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_emp_adhaar_alter_emp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='adhaar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='emp',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
