# Generated by Django 6.0.1 on 2026-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_emp_adhaar_alter_emp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep',
            name='dept_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
