# Generated by Django 6.0.1 on 2026-01-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('quali', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('Document', models.FileField(upload_to='')),
                ('extra', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
