# Generated by Django 6.0.1 on 2026-01-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dep',
            name='dept_emp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
