# Generated by Django 6.0.1 on 2026-02-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
