# Generated by Django 6.0.1 on 2026-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_query_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='admin_rep',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
