# Generated by Django 6.0.1 on 2026-02-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_query_admin_rep_alter_query_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Query',
            field=models.CharField(),
        ),
    ]
