# Generated by Django 6.0.1 on 2026-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_query_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Query',
            field=models.TextField(),
        ),
    ]
